import './published-three-assets.js';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {createGrassSpecimen} from './landscape.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {createArcade,createConservatory,createConservatoryR9,createConservatoryR10,createConservatoryR11,createWaterGarden,createWaterGardenR9,createWaterGardenR10,createGardenBorder,loadHerbariumAssets,loadHerbariumIvyAssets,disposeHerbariumAsset,getHerbariumMaterials,getHerbariumLighting,loadHerbariumBotanicalAssets,createHerbariumBotanicalSpecimen} from './herbarium-assets.js';
import {loadShrubAssets,loadHerbariumCommunityAssets,createShrubSpecimen,createHerbariumCommunity,disposeCommunityAsset,setShrubMaterialMode,getShrubMaterialMode,getShrubNormalSourceState} from './herbarium-community.js';

import {selectShrubNormalEncoding,canRestoreShrubNormal,shrubNormalCapabilities} from './herbarium-normal-policy.js';

const el=id=>document.getElementById(id),query=new URLSearchParams(location.search),canvas=document.querySelector('canvas'),factories={grass:createGrassSpecimen,arcade:createArcade,conservatory:createConservatory,water:createWaterGarden,border:createGardenBorder,community:createHerbariumCommunity},sourceKinds=['fern_02','periwinkle_plant','potted_plant_01','didelta_spinosa'];
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(39,1,.04,200),renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});
renderer.setPixelRatio(devicePixelRatio||1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;
const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.minDistance=.5;controls.maxDistance=70;
const hemi=new THREE.HemisphereLight('#e8f0e8','#60624c',1.75);scene.add(hemi);
const key=new THREE.DirectionalLight('#fff1d9',3.2);key.position.set(-9,17,10);key.castShadow=true;key.shadow.mapSize.set(4096,4096);Object.assign(key.shadow.camera,{left:-15,right:15,top:13,bottom:-13,near:.1,far:55});key.shadow.normalBias=.012;key.shadow.bias=-.00006;scene.add(key,key.target);
const fill=new THREE.DirectionalLight('#c6dceb',.7);fill.position.set(10,8,-6);scene.add(fill);
const room=new RoomEnvironment(),pmrem=new THREE.PMREMGenerator(renderer),environment=pmrem.fromScene(room,.04);scene.environment=environment.texture;scene.environmentIntensity=.42;room.dispose();pmrem.dispose();
const floor=new THREE.Mesh(new THREE.PlaneGeometry(180,180),new THREE.MeshStandardMaterial({color:'#969b90',roughness:.95}));floor.rotation.x=-Math.PI/2;floor.position.y=-.265;floor.receiveShadow=true;scene.add(floor);
const mannequin=new THREE.Group(),scaleMaterial=new THREE.MeshStandardMaterial({color:'#647365',roughness:.83});
function scalePart(geometry,x,y,z){const m=new THREE.Mesh(geometry,scaleMaterial);m.position.set(x,y,z);m.castShadow=true;mannequin.add(m);}
scalePart(new THREE.CapsuleGeometry(.30,1.10,8,16),0,2.05,0);scalePart(new THREE.SphereGeometry(.27,20,16),0,3.01,0);
for(const side of[-1,1]){scalePart(new THREE.CapsuleGeometry(.13,.95,8,12),side*.20,.68,0);scalePart(new THREE.CapsuleGeometry(.105,.91,8,12),side*.48,1.97,0);scalePart(new THREE.BoxGeometry(.28,.15,.50),side*.20,.075,.10);}mannequin.name='3.28 m scale mannequin, not a character asset';scene.add(mannequin);
let group=null,kind=(factories[query.get('kind')]||sourceKinds.includes(query.get('kind')))?query.get('kind'):'conservatory',view=query.get('view')||'threequarter',light=query.get('light')||'neutral',disposed=false,suspended=false,raf=0;
el('vine').value=['outer-left','outer-right'].includes(query.get('vine'))?query.get('vine'):'legacy';
el('shrub-material').value=['source','direct','reflection'].includes(query.get('shrub-material'))?query.get('shrub-material'):'direct';setShrubMaterialMode(el('shrub-material').value);
let normalSelection=null,normalRestoreFailure=null,graphicsPaused=false,assetReadyState='loading',graphicsEpoch=0;
function syncStudyReadiness(){
  document.body.dataset.ready=normalRestoreFailure?'failed':graphicsPaused?'graphics-paused':assetReadyState;
  el('save-frame').disabled=disposed||graphicsPaused||assetReadyState!=='true'||!group;
  if(normalRestoreFailure)for(const input of document.querySelectorAll('select,button,input'))input.disabled=true;
}
function setStudyReady(next){assetReadyState=normalRestoreFailure?'failed':next;syncStudyReadiness();}
function shrubOptions(){normalSelection??=selectShrubNormalEncoding(renderer);return {deadline:performance.now()+120000,signal:loadController.signal,normalEncoding:normalSelection.encoding};}
const urls=new Map(),captureControllers=new Set();let selectionToken=0;const loadController=new AbortController();
function disposeStudy(asset){if(asset?.userData.studyOwner==='grass')asset.dispose();else if(asset?.userData.studyOwner==='community')disposeCommunityAsset(asset);else disposeHerbariumAsset(asset);}
function status(message,error=false){el('status').textContent=message;el('status').dataset.error=String(error);}
function setView(next){view=next;camera.fov=39;camera.updateProjectionMatrix();if(group?.userData.studyViews){const frame=group.userData.studyViews[next]||group.userData.studyViews.threequarter;camera.near=.01;camera.fov=frame.fov||39;camera.updateProjectionMatrix();controls.minDistance=.06;camera.position.fromArray(frame.eye);controls.target.fromArray(frame.target);controls.update();document.querySelectorAll('[data-view]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.view===view)));return;}if(group?.userData.botanicalSource){const d=group.userData.dimensions,span=Math.max(d.width,d.depth,d.height,.3),target=new THREE.Vector3(0,d.height*.48,0),offset={front:[0,.10,2.6],profile:[2.6,.10,0],back:[0,.10,-2.6],overview:[1.1,2.5,1.3],close:[.75,.40,1.15],eye:[1.1,.55,1.6],interior:[1.1,.55,1.6],threequarter:[1.9,1.0,2.1]}[next]||[1.9,1,2.1];camera.near=.005;camera.updateProjectionMatrix();camera.position.copy(target).add(new THREE.Vector3(...offset).multiplyScalar(span));controls.target.copy(target);controls.minDistance=.025;controls.update();document.querySelectorAll('[data-view]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.view===view)));return;}camera.near=.04;controls.minDistance=.5;const house=kind==='conservatory',small=kind==='border',arcade=kind==='arcade',target=new THREE.Vector3(0,house?2.65:arcade?2.2:small?.40:.15,0);const views={threequarter:[19,house?12:10,21],front:[0,house?6:arcade?4.5:small?5:9,house?25:small?16:23],profile:[house?25:23,house?6:arcade?4.6:5,0],back:[0,house?7:8,-25],overview:[13,house?22:20,15]};
  if(arcade&&group.userData.vineComposition&&['vine-root','vine-crown','close'].includes(next)){
    const side=group.userData.vineComposition.kind==='outer-left'?-1:1,outer=side*5.76;
    if(next==='vine-root'){target.set(outer,.28,1.65);camera.position.copy(target).add(new THREE.Vector3(side*.9,.42,2.25));}
    else if(next==='vine-crown'){target.set(outer-side*1.55,4.92,1.50);camera.position.copy(target).add(new THREE.Vector3(side*.8,1.35,6.2));}
    else{target.set(outer-side*.85,2.7,1.52);camera.position.copy(target).add(new THREE.Vector3(side*1.2,.8,10.7));}
  }
  else if(next==='close'){target.set(house?-1.6:arcade?-2.88:kind==='water'?-3.2:1,house?3.5:arcade?3.7:kind==='water'?.22:.42,house?4.05:arcade?1.42:kind==='water'?-.5:0);camera.position.copy(target).add(new THREE.Vector3(house?2.8:3,2.0,house?5:4.0));}
  else if(next==='eye'){target.set(0,house?2.6:arcade?2.2:.45,0);camera.position.set(house?1.2:7,3.05,house?11:13);}
  else if(next==='interior'){if(arcade&&group.userData.vineComposition){const side=group.userData.vineComposition.kind==='outer-left'?-1:1;camera.position.set(-side*3.1,1.70,.05);target.set(side*5.70,3.34,1.49);}else if(house){camera.position.set(.0,2.78,3.63);target.set(5.4,1.55,-1.30);}else{camera.position.set(kind==='water'?5:4,kind==='water'?1.8:3.15,kind==='water'?3.2:0);target.set(kind==='water'?-2:-4,kind==='water'?.25:2.4,0);}}
  else camera.position.fromArray(views[next]||views.threequarter);
  controls.target.copy(target);controls.update();document.querySelectorAll('[data-view]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.view===view)));
}
function setWaterOptics(mode){const m=getHerbariumMaterials().water,refraction=mode==='refraction';Object.assign(m,{transmission:refraction?.965:0,thickness:refraction?.48:0,transparent:!refraction,opacity:refraction?1:.88,depthWrite:refraction,metalness:refraction?0:.035,roughness:refraction?.045:.075});m.color.set(refraction?'#e0eeea':'#426558');m.needsUpdate=true;el('water-optics').value=mode;}
function setLight(mode){light=mode;const night=mode==='night',day=mode==='day';scene.background=new THREE.Color(night?'#23384b':day?'#b8c7c1':'#a7afa5');floor.material.color.set(night?'#56656a':day?'#919e86':'#989f94');key.color.set(night?'#c2d5f2':'#fff1d9');key.intensity=night?1.0:day?3.4:2.8;hemi.intensity=night?.65:1.7;fill.intensity=night?.4:.7;scene.environmentIntensity=night?.25:.42;const assetLighting=getHerbariumLighting(group);for(const {light:lamp,baseIntensity}of assetLighting.lights)lamp.intensity=night?baseIntensity:0;for(const {material,baseIntensity}of assetLighting.emissiveMaterials)material.emissiveIntensity=baseIntensity*(night?1:.08);el('light').value=mode;}
async function setKind(next){
  if(graphicsPaused)throw new Error('Graphics paused; restore the context or reload before selecting an asset.');
  if(!factories[next]&&!sourceKinds.includes(next))throw new RangeError(`Unknown asset: ${next}`);
  const token=++selectionToken,oldKind=kind,selectedVine=el('vine').value,selectedVariant=next===kind?Number(el('variant').value)||0:0;el('kind').disabled=true;el('load-selected').disabled=true;el('save-frame').disabled=true;setStudyReady('loading');status(`Preparing ${next}…`);
  // Return the UI event promptly; leave a visible loading frame before CPU mesh construction.
  await new Promise(resolve=>setTimeout(resolve,60));
  try{
    if(next==='community')await loadHerbariumCommunityAssets(shrubOptions());
    else if(next==='didelta_spinosa')await loadShrubAssets(shrubOptions());
    else if(sourceKinds.includes(next))await loadHerbariumBotanicalAssets({kind:next,deadline:performance.now()+60000,signal:loadController.signal});
    if(next==='arcade'&&selectedVine!=='legacy')await loadHerbariumIvyAssets({deadline:performance.now()+60000,signal:loadController.signal});
    if(disposed||token!==selectionToken)return;
    const studyFactory=query.get('candidate')==='r9'?{conservatory:createConservatoryR9,water:createWaterGardenR9}[next]:query.get('candidate')==='r11'?{conservatory:createConservatoryR11,water:createWaterGardenR10}[next]:query.get('candidate')==='r10'?{conservatory:createConservatoryR10,water:createWaterGardenR10}[next]:null;
    const candidate=next==='didelta_spinosa'?createShrubSpecimen({variant:selectedVariant}):sourceKinds.includes(next)?createHerbariumBotanicalSpecimen(next,{variant:selectedVariant}):next==='arcade'?createArcade({vine:selectedVine}):(studyFactory||factories[next])();
    candidate.traverse(mesh=>{if(mesh.isMesh)for(const material of Array.isArray(mesh.material)?mesh.material:[mesh.material])material.wireframe=el('wireframe').checked;});
    disposeStudy(group);group=candidate;kind=next;floor.position.y=group.userData.studyFloorY??group.userData.actualBounds.min[1]-.004;scene.add(group);el('kind').value=kind;
    el('specimen-controls').hidden=!group.userData.botanicalSource;el('water-controls').hidden=kind!=='water';el('vine-controls').hidden=kind!=='arcade';el('shrub-material-controls').hidden=!['community','didelta_spinosa'].includes(kind);
    if(group.userData.botanicalSource){const source=group.userData.botanicalSource;el('variant').replaceChildren(...source.variants.map((name,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=name;return o;}));el('variant').value=String(source.variantIndex);mannequin.visible=false;el('scale').checked=false;}
    else{if(kind==='grass')el('scale').checked=false;if(kind==='community'&&oldKind!==kind)el('scale').checked=true;mannequin.visible=el('scale').checked;mannequin.position.set(kind==='community'?-6.35:kind==='border'?-6.7:kind==='arcade'?-6.8:8.6,0,kind==='water'?1.8:2.5);}
    setView(view);setLight(light);status(group.userData.botanicalSource?`${group.name} · original full-detail ${group.userData.botanicalSource.resolution===8192?'8K':'4K'} source · CC0`:`${group.name} · actual authored geometry`);setStudyReady('true');
  }catch(error){if(token===selectionToken){el('kind').value=oldKind;el('vine').value=group?.userData.vineComposition?.kind||'legacy';setStudyReady(group?'true':'failed');}throw error;}
  finally{if(!disposed&&token===selectionToken){el('kind').disabled=false;el('load-selected').disabled=false;syncStudyReadiness();}}
}
function evidence(){return {kind,view,light,assetLighting:getHerbariumLighting(group).lights.map(({light:lamp,baseIntensity})=>({name:lamp.name,intensity:lamp.intensity,baseIntensity})),herbariumNormal:{selection:normalSelection,currentCapabilities:shrubNormalCapabilities(renderer),source:getShrubNormalSourceState(),restoreFailure:normalRestoreFailure,graphicsPaused},candidate:query.get('candidate')||null,shrubMaterial:['community','didelta_spinosa'].includes(kind)?getShrubMaterialMode():null,vineComposition:kind==='arcade'?(group?.userData.vineComposition?.kind||'legacy'):null,windEnvelope:group?.userData.vineComposition?.maxWindDisplacement??null,ivySource:group?.userData.vineComposition?.source||null,communitySource:group?.userData.community?{manifest:group.userData.sourceManifest,assets:group.userData.sourceAssets,roots:group.userData.plantRoots.length,windEnvelope:group.userData.maxWindDisplacement}:null,waterOptics:kind==='water'?el('water-optics').value:null,assetVersion:group?.userData.version,botanicalSource:group?.userData.botanicalSource||null,bounds:group?.userData.actualBounds,mannequinVisible:mannequin.visible,scaleHeight:3.28,wireframe:el('wireframe').checked,camera:camera.position.toArray(),target:controls.target.toArray(),nativeViewport:{cssWidth:canvas.clientWidth,cssHeight:canvas.clientHeight,pixelWidth:canvas.width,pixelHeight:canvas.height,devicePixelRatio:devicePixelRatio||1,renderPixelRatio:renderer.getPixelRatio()},render:structuredClone(renderer.info.render)};}
async function saveBlob(name,blob,expectedGraphicsEpoch){const controller=new AbortController();captureControllers.add(controller);const timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(`/__review_capture/${name}`,{method:'POST',body:blob,signal:controller.signal});if(response.ok&&expectedGraphicsEpoch===graphicsEpoch&&!graphicsPaused)return 'server';}catch{/* Static preview falls back to a local download. */}finally{clearTimeout(timer);captureControllers.delete(controller);}if(disposed||suspended||graphicsPaused||expectedGraphicsEpoch!==graphicsEpoch)throw new Error('Capture cancelled when leaving the studio or losing graphics.');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();urls.set(url,setTimeout(()=>{URL.revokeObjectURL(url);urls.delete(url);},60000));return 'download';}
async function saveFrame(){if(!group||disposed||suspended||graphicsPaused)throw new Error('Studio asset is unavailable.');const expectedGraphicsEpoch=graphicsEpoch;renderer.render(scene,camera);const metadata=evidence(),label=[query.get('candidate'),kind==='arcade'?metadata.vineComposition:null,metadata.shrubMaterial].filter(Boolean).map(value=>value.replace(/[^a-z0-9_-]+/gi,'-').slice(0,48)).join('-'),name=`herbarium-${kind}-${label?label+'-':''}${view}-${light}-${Date.now()}.png`,blob=await new Promise((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('Canvas frame encoding failed.')),'image/png'));if(disposed||suspended||graphicsPaused||expectedGraphicsEpoch!==graphicsEpoch)throw new Error('Capture cancelled when leaving the studio or losing graphics.');const destination=await saveBlob(name,blob,expectedGraphicsEpoch);await saveBlob(name.replace('.png','.json'),new Blob([JSON.stringify(metadata,null,2)],{type:'application/json'}),expectedGraphicsEpoch);status(`${destination==='server'?'Saved':'Downloaded'} ${name}`);return name;}
function safely(fn){return async()=>{try{await fn();}catch(error){status(error.message,true);}};}
el('kind').onchange=safely(()=>setKind(el('kind').value));el('load-selected').onclick=safely(()=>document.body.dataset.ready==='failed'&&!group?start():setKind(el('kind').value));el('variant').onchange=safely(()=>setKind(kind));el('vine').onchange=safely(()=>setKind(kind));el('water-optics').onchange=()=>setWaterOptics(el('water-optics').value);el('light').onchange=()=>setLight(el('light').value);el('shrub-material').onchange=()=>setShrubMaterialMode(el('shrub-material').value);el('scale').onchange=()=>{mannequin.visible=el('scale').checked;};el('wireframe').onchange=()=>{for(const m of Object.values(getHerbariumMaterials()))m.wireframe=el('wireframe').checked;group?.traverse(mesh=>{if(mesh.isMesh)for(const m of Array.isArray(mesh.material)?mesh.material:[mesh.material])m.wireframe=el('wireframe').checked;});};el('save-frame').onclick=safely(saveFrame);document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>setView(button.dataset.view));
function resize(){if(disposed||suspended)return;renderer.setPixelRatio(devicePixelRatio||1);renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);camera.aspect=canvas.clientWidth/canvas.clientHeight;camera.updateProjectionMatrix();}
const observer=new ResizeObserver(resize);observer.observe(canvas);resize();setLight(light);setWaterOptics(query.get('water-optics')||'surface');

function frame(){if(disposed||suspended||graphicsPaused)return;raf=requestAnimationFrame(frame);if(document.hidden)return;controls.update();renderer.render(scene,camera);if(group){const d=group.userData.dimensions;el('readout').textContent=`${d.width.toFixed(2)} × ${d.depth.toFixed(2)} × ${d.height.toFixed(2)} m envelope\n${renderer.info.render.triangles.toLocaleString()} rendered triangles\n${group.children.filter(mesh=>mesh.isMesh).length} asset material batches\n${group.userData.community?`${group.userData.plantRoots.length} rooted plants\n`:''}Native ${canvas.width} × ${canvas.height}\nDPR ${renderer.getPixelRatio()}`;}}raf=requestAnimationFrame(frame);
canvas.addEventListener('webglcontextlost',event=>{event.preventDefault();graphicsEpoch++;graphicsPaused=true;cancelAnimationFrame(raf);for(const controller of captureControllers)controller.abort();syncStudyReadiness();status('Graphics paused. Wait for restore or reload; full source quality is retained.',true);});
canvas.addEventListener('webglcontextrestored',()=>{
  if(disposed)return;graphicsEpoch++;
  if(normalSelection&&!canRestoreShrubNormal(renderer,normalSelection.encoding)){normalRestoreFailure=shrubNormalCapabilities(renderer);graphicsPaused=true;selectionToken++;loadController.abort(new Error('Restored renderer cannot retain selected shrub normal'));setStudyReady('failed');status('Graphics capability changed. Reload to select supported full-quality source assets.',true);return;}
  normalRestoreFailure=null;graphicsPaused=false;renderer.shadowMap.needsUpdate=true;syncStudyReadiness();if(!suspended){resize();cancelAnimationFrame(raf);raf=requestAnimationFrame(frame);}status('Graphics restored with the same source encoding.');
});
window.__herbariumStudio={scene,camera,renderer,controls,get asset(){return group;},setKind,setView,setLight,saveFrame,evidence};
window.addEventListener('pagehide',event=>{if(disposed)return;suspended=true;cancelAnimationFrame(raf);observer.disconnect();if(event.persisted)return;disposed=true;selectionToken++;loadController.abort();for(const controller of captureControllers)controller.abort();captureControllers.clear();for(const[url,timer]of urls){clearTimeout(timer);URL.revokeObjectURL(url);}urls.clear();disposeStudy(group);controls.dispose();floor.geometry.dispose();floor.material.dispose();mannequin.traverse(mesh=>{if(mesh.isMesh)mesh.geometry.dispose();});scaleMaterial.dispose();environment.dispose();key.shadow.map?.dispose();key.shadow.mapPass?.dispose();renderer.dispose();});
window.addEventListener('pageshow',event=>{if(!event.persisted||disposed||!suspended)return;suspended=false;observer.observe(canvas);resize();raf=requestAnimationFrame(frame);});

async function start(){
  setStudyReady('loading');document.querySelector('aside').setAttribute('aria-busy','true');for(const input of document.querySelectorAll('select,button,input'))input.disabled=true;status('Loading physical materials and botanical sources…');
  try{await loadHerbariumAssets({regional:false,deadline:performance.now()+30000,signal:loadController.signal});if(disposed)return;await setKind(kind);if(disposed)return;setStudyReady('true');for(const input of document.querySelectorAll('select,button,input'))input.disabled=false;el('load-selected').textContent='Load selected asset';}
  catch(error){if(disposed)return;status(`Herbarium load failed: ${error.message}`,true);setStudyReady('failed');for(const input of document.querySelectorAll('select,button,input'))input.disabled=true;el('load-selected').disabled=false;el('load-selected').textContent='Retry asset loading';}
  finally{if(!disposed){document.querySelector('aside').setAttribute('aria-busy','false');syncStudyReadiness();}}
}
await start();
